package com.notesapp.designsystem.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF1A73E8)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD3E3FD)
val LightOnPrimaryContainer = Color(0xFF041E49)
val LightSecondary = Color(0xFF5F6368)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE8EAED)
val LightOnSecondaryContainer = Color(0xFF1F1F1F)
val LightSurface = Color(0xFFFFFBFE)
val LightOnSurface = Color(0xFF1C1B1F)
val LightSurfaceVariant = Color(0xFFF1F3F4)
val LightOnSurfaceVariant = Color(0xFF49454F)
val LightBackground = Color(0xFFFFFBFE)
val LightOnBackground = Color(0xFF1C1B1F)
val LightError = Color(0xFFB3261E)
val LightOnError = Color(0xFFFFFFFF)
val LightOutline = Color(0xFF79747E)

val DarkPrimary = Color(0xFF8AB4F8)
val DarkOnPrimary = Color(0xFF062E6F)
val DarkPrimaryContainer = Color(0xFF0842A0)
val DarkOnPrimaryContainer = Color(0xFFD3E3FD)
val DarkSecondary = Color(0xFFC4C7C5)
val DarkOnSecondary = Color(0xFF303134)
val DarkSecondaryContainer = Color(0xFF3C4043)
val DarkOnSecondaryContainer = Color(0xFFE8EAED)
val DarkSurface = Color(0xFF1C1B1F)
val DarkOnSurface = Color(0xFFE6E1E5)
val DarkSurfaceVariant = Color(0xFF303134)
val DarkOnSurfaceVariant = Color(0xFFCAC4D0)
val DarkBackground = Color(0xFF1C1B1F)
val DarkOnBackground = Color(0xFFE6E1E5)
val DarkError = Color(0xFFF2B8B5)
val DarkOnError = Color(0xFF601410)
val DarkOutline = Color(0xFF938F99)

val NoteRed = Color(0xFFF28B82)
val NoteOrange = Color(0xFFFBBC04)
val NoteYellow = Color(0xFFFFF475)
val NoteGreen = Color(0xFFA8DAB5)
val NoteTeal = Color(0xFFA7FFEB)
val NoteBlue = Color(0xFFCBF0F8)
val NotePurple = Color(0xFFD7AEFB)
val NotePink = Color(0xFFFECDD3)

val NoteAccentColors = listOf(null, NoteRed, NoteOrange, NoteYellow, NoteGreen, NoteTeal, NoteBlue, NotePurple, NotePink)
